/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { PostAppWhereInput } from "./PostAppWhereInput";
import { Type } from "class-transformer";
import { PostAppOrderByInput } from "./PostAppOrderByInput";

@ArgsType()
class PostAppFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => PostAppWhereInput,
  })
  @Field(() => PostAppWhereInput, { nullable: true })
  @Type(() => PostAppWhereInput)
  where?: PostAppWhereInput;

  @ApiProperty({
    required: false,
    type: PostAppOrderByInput,
  })
  @Field(() => PostAppOrderByInput, { nullable: true })
  @Type(() => PostAppOrderByInput)
  orderBy?: PostAppOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { PostAppFindManyArgs };
